[tox]
envlist = lint,test

[testenv:lint]
skip_install = true
deps = ruff
commands = ruff check . 

[testenv:test]
skip_install = true
install_command=pip install {opts} {packages}
deps =
    -r requirements.txt
    pytest
    pytest-asyncio
commands = pytest


[testenv:format]
skip_install = true
deps = ruff
commands = ruff format .